/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.4.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/blockx_rust.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export type Result = {
    __kind__: "Ok";
    Ok: string;
} | {
    __kind__: "Err";
    Err: ServiceError;
};
export interface Asset {
    asset_type: AssetType;
    owner: Principal;
    hash: string;
    created_at: bigint;
    details: AssetDetails;
    category: AssetCategory;
    ownership_proof: Proof;
}
export interface AssetUserInput {
    asset_type: AssetType;
    details: AssetDetails;
    category: AssetCategory;
    ownership_proof: Proof;
}
export interface Proof {
    deed_document: Array<string>;
    deed_reference_number?: string;
    publication_links: Array<string>;
    registration_number?: string;
    license_plate?: string;
    serial_number?: string;
}
export type ServiceError = {
    __kind__: "InvalidCategory";
    InvalidCategory: string;
} | {
    __kind__: "NotFound";
    NotFound: string;
} | {
    __kind__: "AssetAlreadyExists";
    AssetAlreadyExists: string;
} | {
    __kind__: "Unauthorized";
    Unauthorized: string;
} | {
    __kind__: "MissingProof";
    MissingProof: string;
} | {
    __kind__: "InternalError";
    InternalError: string;
};
export interface AssetDetails {
    files: Array<string>;
    manufacturer?: string;
    name: string;
    type?: string;
    description: string;
    address?: string;
}
export enum AssetCategory {
    IntellectualProperty = "IntellectualProperty",
    RealEstate = "RealEstate",
    Vehicle = "Vehicle",
    ValuableItem = "ValuableItem",
    DigitalAsset = "DigitalAsset",
    Equipment = "Equipment"
}
export enum AssetType {
    Physical = "Physical",
    NonPhysical = "NonPhysical"
}
export interface blockx_rustInterface {
    get_assets(arg0: Array<bigint>): Promise<Array<Asset>>;
    get_user_assets(): Promise<Array<Asset>>;
    register_asset(arg0: AssetUserInput): Promise<Result>;
    /**
     * 
     * * should not be used for checking asset uniqueness as it does shallow checking
     * *
     * * Checks if the asset exists by its hash
     * 
     */
    verify_asset(arg0: string, arg1: AssetCategory): Promise<boolean>;
}
import type { Asset as _Asset, AssetCategory as _AssetCategory, AssetDetails as _AssetDetails, AssetType as _AssetType, AssetUserInput as _AssetUserInput, Proof as _Proof, Result as _Result, ServiceError as _ServiceError } from "./declarations/blockx_rust.did";
export class Blockx_rust implements blockx_rustInterface {
    constructor(private actor: ActorSubclass<_SERVICE>){}
    async get_assets(arg0: Array<bigint>): Promise<Array<Asset>> {
        const result = await this.actor.get_assets(arg0);
        return from_candid_vec_n1(result);
    }
    async get_user_assets(): Promise<Array<Asset>> {
        const result = await this.actor.get_user_assets();
        return from_candid_vec_n1(result);
    }
    async register_asset(arg0: AssetUserInput): Promise<Result> {
        const result = await this.actor.register_asset(to_candid_AssetUserInput_n13(arg0));
        return from_candid_Result_n23(result);
    }
    async verify_asset(arg0: string, arg1: AssetCategory): Promise<boolean> {
        const result = await this.actor.verify_asset(arg0, to_candid_AssetCategory_n19(arg1));
        return result;
    }
}
function from_candid_AssetCategory_n9(value: _AssetCategory): AssetCategory {
    return from_candid_variant_n10(value);
}
function from_candid_AssetDetails_n6(value: _AssetDetails): AssetDetails {
    return from_candid_record_n7(value);
}
function from_candid_AssetType_n4(value: _AssetType): AssetType {
    return from_candid_variant_n5(value);
}
function from_candid_Asset_n2(value: _Asset): Asset {
    return from_candid_record_n3(value);
}
function from_candid_Proof_n11(value: _Proof): Proof {
    return from_candid_record_n12(value);
}
function from_candid_Result_n23(value: _Result): Result {
    return from_candid_variant_n24(value);
}
function from_candid_ServiceError_n25(value: _ServiceError): ServiceError {
    return from_candid_variant_n26(value);
}
function from_candid_opt_n8(value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(value: {
    deed_document: Array<string>;
    deed_reference_number: [] | [string];
    publication_links: Array<string>;
    registration_number: [] | [string];
    license_plate: [] | [string];
    serial_number: [] | [string];
}): {
    deed_document: Array<string>;
    deed_reference_number?: string;
    publication_links: Array<string>;
    registration_number?: string;
    license_plate?: string;
    serial_number?: string;
} {
    return {
        deed_document: value.deed_document,
        deed_reference_number: record_opt_to_undefined(from_candid_opt_n8(value.deed_reference_number)),
        publication_links: value.publication_links,
        registration_number: record_opt_to_undefined(from_candid_opt_n8(value.registration_number)),
        license_plate: record_opt_to_undefined(from_candid_opt_n8(value.license_plate)),
        serial_number: record_opt_to_undefined(from_candid_opt_n8(value.serial_number))
    };
}
function from_candid_record_n3(value: {
    asset_type: _AssetType;
    owner: Principal;
    hash: string;
    created_at: bigint;
    details: _AssetDetails;
    category: _AssetCategory;
    ownership_proof: _Proof;
}): {
    asset_type: AssetType;
    owner: Principal;
    hash: string;
    created_at: bigint;
    details: AssetDetails;
    category: AssetCategory;
    ownership_proof: Proof;
} {
    return {
        asset_type: from_candid_AssetType_n4(value.asset_type),
        owner: value.owner,
        hash: value.hash,
        created_at: value.created_at,
        details: from_candid_AssetDetails_n6(value.details),
        category: from_candid_AssetCategory_n9(value.category),
        ownership_proof: from_candid_Proof_n11(value.ownership_proof)
    };
}
function from_candid_record_n7(value: {
    files: Array<string>;
    manufacturer: [] | [string];
    name: string;
    type: [] | [string];
    description: string;
    address: [] | [string];
}): {
    files: Array<string>;
    manufacturer?: string;
    name: string;
    type?: string;
    description: string;
    address?: string;
} {
    return {
        files: value.files,
        manufacturer: record_opt_to_undefined(from_candid_opt_n8(value.manufacturer)),
        name: value.name,
        type: record_opt_to_undefined(from_candid_opt_n8(value.type)),
        description: value.description,
        address: record_opt_to_undefined(from_candid_opt_n8(value.address))
    };
}
function from_candid_variant_n10(value: {
    IntellectualProperty: null;
} | {
    RealEstate: null;
} | {
    Vehicle: null;
} | {
    ValuableItem: null;
} | {
    DigitalAsset: null;
} | {
    Equipment: null;
}): AssetCategory {
    return "IntellectualProperty" in value ? AssetCategory.IntellectualProperty : "RealEstate" in value ? AssetCategory.RealEstate : "Vehicle" in value ? AssetCategory.Vehicle : "ValuableItem" in value ? AssetCategory.ValuableItem : "DigitalAsset" in value ? AssetCategory.DigitalAsset : "Equipment" in value ? AssetCategory.Equipment : value;
}
function from_candid_variant_n24(value: {
    Ok: string;
} | {
    Err: _ServiceError;
}): {
    __kind__: "Ok";
    Ok: string;
} | {
    __kind__: "Err";
    Err: ServiceError;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: from_candid_ServiceError_n25(value.Err)
    } : value;
}
function from_candid_variant_n26(value: {
    InvalidCategory: string;
} | {
    NotFound: string;
} | {
    AssetAlreadyExists: string;
} | {
    Unauthorized: string;
} | {
    MissingProof: string;
} | {
    InternalError: string;
}): {
    __kind__: "InvalidCategory";
    InvalidCategory: string;
} | {
    __kind__: "NotFound";
    NotFound: string;
} | {
    __kind__: "AssetAlreadyExists";
    AssetAlreadyExists: string;
} | {
    __kind__: "Unauthorized";
    Unauthorized: string;
} | {
    __kind__: "MissingProof";
    MissingProof: string;
} | {
    __kind__: "InternalError";
    InternalError: string;
} {
    return "InvalidCategory" in value ? {
        __kind__: "InvalidCategory",
        InvalidCategory: value.InvalidCategory
    } : "NotFound" in value ? {
        __kind__: "NotFound",
        NotFound: value.NotFound
    } : "AssetAlreadyExists" in value ? {
        __kind__: "AssetAlreadyExists",
        AssetAlreadyExists: value.AssetAlreadyExists
    } : "Unauthorized" in value ? {
        __kind__: "Unauthorized",
        Unauthorized: value.Unauthorized
    } : "MissingProof" in value ? {
        __kind__: "MissingProof",
        MissingProof: value.MissingProof
    } : "InternalError" in value ? {
        __kind__: "InternalError",
        InternalError: value.InternalError
    } : value;
}
function from_candid_variant_n5(value: {
    Physical: null;
} | {
    NonPhysical: null;
}): AssetType {
    return "Physical" in value ? AssetType.Physical : "NonPhysical" in value ? AssetType.NonPhysical : value;
}
function from_candid_vec_n1(value: Array<_Asset>): Array<Asset> {
    return value.map((x)=>from_candid_Asset_n2(x));
}
function to_candid_AssetCategory_n19(value: AssetCategory): _AssetCategory {
    return to_candid_variant_n20(value);
}
function to_candid_AssetDetails_n17(value: AssetDetails): _AssetDetails {
    return to_candid_record_n18(value);
}
function to_candid_AssetType_n15(value: AssetType): _AssetType {
    return to_candid_variant_n16(value);
}
function to_candid_AssetUserInput_n13(value: AssetUserInput): _AssetUserInput {
    return to_candid_record_n14(value);
}
function to_candid_Proof_n21(value: Proof): _Proof {
    return to_candid_record_n22(value);
}
function to_candid_record_n14(value: {
    asset_type: AssetType;
    details: AssetDetails;
    category: AssetCategory;
    ownership_proof: Proof;
}): {
    asset_type: _AssetType;
    details: _AssetDetails;
    category: _AssetCategory;
    ownership_proof: _Proof;
} {
    return {
        asset_type: to_candid_AssetType_n15(value.asset_type),
        details: to_candid_AssetDetails_n17(value.details),
        category: to_candid_AssetCategory_n19(value.category),
        ownership_proof: to_candid_Proof_n21(value.ownership_proof)
    };
}
function to_candid_record_n18(value: {
    files: Array<string>;
    manufacturer?: string;
    name: string;
    type?: string;
    description: string;
    address?: string;
}): {
    files: Array<string>;
    manufacturer: [] | [string];
    name: string;
    type: [] | [string];
    description: string;
    address: [] | [string];
} {
    return {
        files: value.files,
        manufacturer: value.manufacturer ? candid_some(value.manufacturer) : candid_none(),
        name: value.name,
        type: value.type ? candid_some(value.type) : candid_none(),
        description: value.description,
        address: value.address ? candid_some(value.address) : candid_none()
    };
}
function to_candid_record_n22(value: {
    deed_document: Array<string>;
    deed_reference_number?: string;
    publication_links: Array<string>;
    registration_number?: string;
    license_plate?: string;
    serial_number?: string;
}): {
    deed_document: Array<string>;
    deed_reference_number: [] | [string];
    publication_links: Array<string>;
    registration_number: [] | [string];
    license_plate: [] | [string];
    serial_number: [] | [string];
} {
    return {
        deed_document: value.deed_document,
        deed_reference_number: value.deed_reference_number ? candid_some(value.deed_reference_number) : candid_none(),
        publication_links: value.publication_links,
        registration_number: value.registration_number ? candid_some(value.registration_number) : candid_none(),
        license_plate: value.license_plate ? candid_some(value.license_plate) : candid_none(),
        serial_number: value.serial_number ? candid_some(value.serial_number) : candid_none()
    };
}
function to_candid_variant_n16(value: AssetType): {
    Physical: null;
} | {
    NonPhysical: null;
} {
    return value == AssetType.Physical ? {
        Physical: null
    } : value == AssetType.NonPhysical ? {
        NonPhysical: null
    } : value;
}
function to_candid_variant_n20(value: AssetCategory): {
    IntellectualProperty: null;
} | {
    RealEstate: null;
} | {
    Vehicle: null;
} | {
    ValuableItem: null;
} | {
    DigitalAsset: null;
} | {
    Equipment: null;
} {
    return value == AssetCategory.IntellectualProperty ? {
        IntellectualProperty: null
    } : value == AssetCategory.RealEstate ? {
        RealEstate: null
    } : value == AssetCategory.Vehicle ? {
        Vehicle: null
    } : value == AssetCategory.ValuableItem ? {
        ValuableItem: null
    } : value == AssetCategory.DigitalAsset ? {
        DigitalAsset: null
    } : value == AssetCategory.Equipment ? {
        Equipment: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
}
export function createActor(canisterId: string, options: CreateActorOptions = {}): Blockx_rust {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Blockx_rust(actor);
}
