/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.4.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Asset {
  'asset_type' : AssetType,
  'owner' : Principal,
  'hash' : string,
  'created_at' : bigint,
  'details' : AssetDetails,
  'category' : AssetCategory,
  'ownership_proof' : Proof,
}
export type AssetCategory = { 'IntellectualProperty' : null } |
  { 'RealEstate' : null } |
  { 'Vehicle' : null } |
  { 'ValuableItem' : null } |
  { 'DigitalAsset' : null } |
  { 'Equipment' : null };
export interface AssetDetails {
  'files' : Array<string>,
  'manufacturer' : [] | [string],
  'name' : string,
  'type' : [] | [string],
  'description' : string,
  'address' : [] | [string],
}
export type AssetType = { 'Physical' : null } |
  { 'NonPhysical' : null };
export interface AssetUserInput {
  'asset_type' : AssetType,
  'details' : AssetDetails,
  'category' : AssetCategory,
  'ownership_proof' : Proof,
}
export interface Proof {
  'deed_document' : Array<string>,
  'deed_reference_number' : [] | [string],
  'publication_links' : Array<string>,
  'registration_number' : [] | [string],
  'license_plate' : [] | [string],
  'serial_number' : [] | [string],
}
export type Result = { 'Ok' : string } |
  { 'Err' : ServiceError };
export type ServiceError = { 'InvalidCategory' : string } |
  { 'NotFound' : string } |
  { 'AssetAlreadyExists' : string } |
  { 'Unauthorized' : string } |
  { 'MissingProof' : string } |
  { 'InternalError' : string };
export interface _SERVICE {
  'get_assets' : ActorMethod<[Array<bigint>], Array<Asset>>,
  'get_user_assets' : ActorMethod<[], Array<Asset>>,
  'register_asset' : ActorMethod<[AssetUserInput], Result>,
  /**
   * 
   * * should not be used for checking asset uniqueness as it does shallow checking
   * *
   * * Checks if the asset exists by its hash
   * 
   */
  'verify_asset' : ActorMethod<[string, AssetCategory], boolean>,
}
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];